# Using PostgreSQL 9.3

development:
  adapter: postgresql
  encoding: unicode
  database: maps_demo
  pool: 5
  username: jozef
  password: password
  template: template_postgis


test:
  adapter: postgresql
  encoding: unicode
  database: maps_demo
  pool: 5
  username: jozef
  password: password
  template: template_postgis


production:
  adapter: postgresql
  encoding: unicode
  database: maps_demo
  pool: 20
  username: jozef
  password: password
  template: template_postgis
